### ISSUE TITLE
[BUG] Process finished with exit code -1073741819 (0xC0000005)

### ISSUE THREAD

**Issue by wukan1986** [pydata/bottleneck#345] opened 2020-05-07 06:42 UTC
Faulting application name: python.exe, version: 3.7.3150.1013, time stamp: 0x5cc0c771
Faulting module name: nonreduce_axis.cp37-win_amd64.pyd, version: 0.0.0.0, time stamp: 0x5e53ee01
Exception code: 0xc0000005
Fault offset: 0x0000000000001357
Faulting process id: 0x57a0
Faulting application start time: 0x01d62438f31b5658
Faulting application path: D:\Users\Kan\Anaconda3\python.exe
Faulting module path: D:\Users\Kan\Anaconda3\lib\site-packages\bottleneck\nonreduce_axis.cp37-win_amd64.pyd
Report Id: 80791a2c-11bf-41e7-b89a-bdc6e5d8569b
Faulting package full name: 
Faulting package-relative application ID: 

Bottleneck  1.3.2
pandas  1.0.3
numpy 1.18.1

**Comment by wukan1986** [comment] 2020-05-07 09:42
i think nanrankdata will crash if memory overflow

**Comment by qwhelan** [comment] 2020-05-07 23:32
Thanks for reporting, will investigate over the weekend

**Comment by qwhelan** [comment] 2020-05-22 20:17
I'm able to confirm there's a leak here when dealing with arrays of `ndim > 1`. Investigating with valgrind to identify the root cause.

**Comment by qwhelan** [comment] 2020-05-23 03:47
The `CLOSE` array is about 700MB and is being copied in each iteration. Eliminating storage in `dict_` should solve the issue, and triggering `gc.collect()` should help further if memory usage is accumulating too quickly.

Closing as there does not appear to be a leak.

**Closed by qwhelan** 2020-05-23 03:47 UTC
Labels: bug

**Comment by wukan1986** [comment] 2020-05-26 00:32
I think throw an exception is friendly than crash directly
